### ISSUE TITLE
Remove default categories, categoryOptions, etc and references

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/Advanced-Metadata-Export#3]
Redmine issue:
http://who-dev.essi.upc.edu:8083/issues/1243

When exporting and importing on a new server, the default objects are always colliding and the json file has to be filtered in order to remove those references. This could be a new option in the app

**Comment by SferaDev** [comment]
In PR #6 we have now completely disabled elements with code === 'default'. I don't see the point of adding an option to allow it, but we can discuss if it makes sense.

**Comment by ifoche** [comment]
@SferaDev the resulting json file still contains the references to the UIDs of the default category/cat option/cat combination/etc. The consequence is that you cannot directly import that json, because those UIDs are not valid in the destination DHIS2 instance. Could you have a look to it? IMHO, an extra option to remove the default cat/cat combo/cat option/etc may be useful. As far as I know, when you don't assign a cat option to something, DHIS2 assumes the default one, so removing them from the json should be safe...what do you think?

**Comment by SferaDev** [comment]
Okay, so the problem is not only that we do not parse them, but that the references are still there. I guess we have DHIS2 ids instead of codes. As you say we could add a clean-up option that asks the api for the ids of the instance that have code "default" and remove them (as ids) directly from the json. I'll try to add it tonight so you can test it with @idelcano tomorrow.
